"""initial migration with kittylog schema and rbac

Revision ID: c740e1518bae
Revises: 
Create Date: 2026-02-22 21:22:10.972469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c740e1518bae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action', 'resource', name='uq_permission_action_resource'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_permission_action'), 'permission', ['action'], unique=False, schema='kittylog')
    op.create_index(op.f('ix_kittylog_permission_id'), 'permission', ['id'], unique=False, schema='kittylog')
    op.create_index(op.f('ix_kittylog_permission_resource'), 'permission', ['resource'], unique=False, schema='kittylog')
    op.create_table('plan',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_plan_id'), 'plan', ['id'], unique=False, schema='kittylog')
    op.create_index(op.f('ix_kittylog_plan_name'), 'plan', ['name'], unique=True, schema='kittylog')
    op.create_table('role',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_role_id'), 'role', ['id'], unique=False, schema='kittylog')
    op.create_index(op.f('ix_kittylog_role_name'), 'role', ['name'], unique=True, schema='kittylog')
    op.create_table('users',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_users_email'), 'users', ['email'], unique=True, schema='kittylog')
    op.create_index(op.f('ix_kittylog_users_full_name'), 'users', ['full_name'], unique=False, schema='kittylog')
    op.create_index(op.f('ix_kittylog_users_id'), 'users', ['id'], unique=False, schema='kittylog')
    op.create_table('cat',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('microchip_number', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['kittylog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_cat_id'), 'cat', ['id'], unique=False, schema='kittylog')
    op.create_table('notificationpreference',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('low_stock_alerts', sa.Boolean(), nullable=True),
    sa.Column('vaccination_reminders', sa.Boolean(), nullable=True),
    sa.Column('appointment_reminders', sa.Boolean(), nullable=True),
    sa.Column('missed_activity_alerts', sa.Boolean(), nullable=True),
    sa.Column('reminder_advance_hours', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['kittylog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_notificationpreference_id'), 'notificationpreference', ['id'], unique=False, schema='kittylog')
    op.create_table('plan_permission',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['kittylog.permission.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['kittylog.plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'permission_id', name='uq_plan_permission'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_plan_permission_id'), 'plan_permission', ['id'], unique=False, schema='kittylog')
    op.create_table('role_permission',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['kittylog.permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['kittylog.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_role_permission_id'), 'role_permission', ['id'], unique=False, schema='kittylog')
    op.create_table('user_role',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['kittylog.role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kittylog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_user_role_id'), 'user_role', ['id'], unique=False, schema='kittylog')
    op.create_table('user_subscription',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['kittylog.plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kittylog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_user_subscription_id'), 'user_subscription', ['id'], unique=False, schema='kittylog')
    op.create_table('activitylog',
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_reason', sa.String(), nullable=True),
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['kittylog.cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_activitylog_id'), 'activitylog', ['id'], unique=False, schema='kittylog')
    op.create_table('appointment',
    sa.Column('appointment_type', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(), nullable=True),
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['kittylog.cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_appointment_id'), 'appointment', ['id'], unique=False, schema='kittylog')
    op.create_table('catvaccine',
    sa.Column('vaccine_name', sa.String(), nullable=False),
    sa.Column('administered_at', sa.DateTime(), nullable=False),
    sa.Column('next_due_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['kittylog.cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_catvaccine_id'), 'catvaccine', ['id'], unique=False, schema='kittylog')
    op.create_table('catweight',
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['kittylog.cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_catweight_id'), 'catweight', ['id'], unique=False, schema='kittylog')
    op.create_table('dailyhealth',
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('ate', sa.Boolean(), nullable=True),
    sa.Column('ate_at', sa.DateTime(), nullable=True),
    sa.Column('used_litter', sa.Boolean(), nullable=True),
    sa.Column('used_litter_at', sa.DateTime(), nullable=True),
    sa.Column('took_medicine', sa.Boolean(), nullable=True),
    sa.Column('took_medicine_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['kittylog.cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_dailyhealth_id'), 'dailyhealth', ['id'], unique=False, schema='kittylog')
    op.create_table('diaryentry',
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('photo_urls', sa.String(), nullable=True),
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['kittylog.cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_diaryentry_id'), 'diaryentry', ['id'], unique=False, schema='kittylog')
    op.create_table('notificationlog',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('cat_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['kittylog.cat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['kittylog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_notificationlog_id'), 'notificationlog', ['id'], unique=False, schema='kittylog')
    op.create_table('supplyitem',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('current_quantity', sa.Float(), nullable=False),
    sa.Column('low_stock_threshold', sa.Float(), nullable=False),
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['kittylog.cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_supplyitem_id'), 'supplyitem', ['id'], unique=False, schema='kittylog')
    op.create_table('vetvisit',
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=True),
    sa.Column('vet_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('cat_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['kittylog.cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_vetvisit_id'), 'vetvisit', ['id'], unique=False, schema='kittylog')
    op.create_table('reminder',
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['kittylog.appointment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_reminder_id'), 'reminder', ['id'], unique=False, schema='kittylog')
    op.create_table('stocklog',
    sa.Column('quantity_added', sa.Float(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('supply_item_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supply_item_id'], ['kittylog.supplyitem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='kittylog'
    )
    op.create_index(op.f('ix_kittylog_stocklog_id'), 'stocklog', ['id'], unique=False, schema='kittylog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kittylog_stocklog_id'), table_name='stocklog', schema='kittylog')
    op.drop_table('stocklog', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_reminder_id'), table_name='reminder', schema='kittylog')
    op.drop_table('reminder', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_vetvisit_id'), table_name='vetvisit', schema='kittylog')
    op.drop_table('vetvisit', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_supplyitem_id'), table_name='supplyitem', schema='kittylog')
    op.drop_table('supplyitem', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_notificationlog_id'), table_name='notificationlog', schema='kittylog')
    op.drop_table('notificationlog', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_diaryentry_id'), table_name='diaryentry', schema='kittylog')
    op.drop_table('diaryentry', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_dailyhealth_id'), table_name='dailyhealth', schema='kittylog')
    op.drop_table('dailyhealth', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_catweight_id'), table_name='catweight', schema='kittylog')
    op.drop_table('catweight', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_catvaccine_id'), table_name='catvaccine', schema='kittylog')
    op.drop_table('catvaccine', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_appointment_id'), table_name='appointment', schema='kittylog')
    op.drop_table('appointment', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_activitylog_id'), table_name='activitylog', schema='kittylog')
    op.drop_table('activitylog', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_user_subscription_id'), table_name='user_subscription', schema='kittylog')
    op.drop_table('user_subscription', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_user_role_id'), table_name='user_role', schema='kittylog')
    op.drop_table('user_role', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_role_permission_id'), table_name='role_permission', schema='kittylog')
    op.drop_table('role_permission', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_plan_permission_id'), table_name='plan_permission', schema='kittylog')
    op.drop_table('plan_permission', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_notificationpreference_id'), table_name='notificationpreference', schema='kittylog')
    op.drop_table('notificationpreference', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_cat_id'), table_name='cat', schema='kittylog')
    op.drop_table('cat', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_users_id'), table_name='users', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_users_full_name'), table_name='users', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_users_email'), table_name='users', schema='kittylog')
    op.drop_table('users', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_role_name'), table_name='role', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_role_id'), table_name='role', schema='kittylog')
    op.drop_table('role', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_plan_name'), table_name='plan', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_plan_id'), table_name='plan', schema='kittylog')
    op.drop_table('plan', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_permission_resource'), table_name='permission', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_permission_id'), table_name='permission', schema='kittylog')
    op.drop_index(op.f('ix_kittylog_permission_action'), table_name='permission', schema='kittylog')
    op.drop_table('permission', schema='kittylog')
    # ### end Alembic commands ###
